apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ecr-credential.serviceAccount" . }}
  namespace: {{ include "aws-ecr-credential.namespace" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-manager
  namespace: {{ include "aws-ecr-credential.namespace" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "create"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aws-ecr-credential.serviceAccount" . }}
  namespace: {{ include "aws-ecr-credential.namespace" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ecr-credential.serviceAccount" . }}
    namespace: {{ include "aws-ecr-credential.namespace" . }}
